
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "cmake-3.29.0-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "cmake-3.29.0-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "cmake-3.29.0-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "cmake-3.29.0-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/trae-bz/TraeProjects/33/tcc/tcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      The C compiler identification is TinyCC, found in:
        D:/trae-bz/TraeProjects/33/build_clean/CMakeFiles/3.29.0/CompilerIdC/CMakeCCompilerId.exe
      
...
